export const INITIAL_PROJECTS = [
  {
    id: 'proj-1',
    name: 'App Móvil Finanzas Pro',
    client: 'FinTech LATAM',
    category: 'Desarrollo Mobile',
    status: 'En Curso',
    budgetARS: 4500000,
    budgetUSD: 3500,
    paidARS: 3000000,
    paidUSD: 2300,
    startDate: '2026-06-01',
    deadline: '2026-10-15',
    teamCostARS: 1200000,
    teamCostUSD: 950,
    description: 'Desarrollo de aplicación móvil iOS/Android para gestión patrimonial con biometría y pasarela de pago.',
    milestones: [
      { name: 'Anticipo 30%', amountARS: 1350000, status: 'Cobrado', date: '2026-06-05' },
      { name: 'Sprint 1 UI & Auth', amountARS: 1650000, status: 'Cobrado', date: '2026-07-20' },
      { name: 'Sprint 2 Integraciones', amountARS: 1500000, status: 'Pendiente', date: '2026-09-25' }
    ]
  },
  {
    id: 'proj-2',
    name: 'E-Commerce SaaS B2B',
    client: 'Distribuidora Global S.A.',
    category: 'Fullstack Web',
    status: 'En Curso',
    budgetARS: 8200000,
    budgetUSD: 6500,
    paidARS: 5000000,
    paidUSD: 4000,
    startDate: '2026-05-15',
    deadline: '2026-11-01',
    teamCostARS: 2100000,
    teamCostUSD: 1650,
    description: 'Plataforma B2B con catálogo multi-sucursal, pedidos automatizados y sincronización con sistema ERP.',
    milestones: [
      { name: 'Anticipo 50%', amountARS: 4100000, status: 'Cobrado', date: '2026-05-20' },
      { name: 'Sprint Backend ERP', amountARS: 900000, status: 'Cobrado', date: '2026-07-10' },
      { name: 'Entrega Final & Launch', amountARS: 3200000, status: 'Pendiente', date: '2026-10-30' }
    ]
  },
  {
    id: 'proj-3',
    name: 'Rediseño de Marca & UI System',
    client: 'Studio Alpha',
    category: 'Branding & UI/UX',
    status: 'Completado',
    budgetARS: 2100000,
    budgetUSD: 1700,
    paidARS: 2100000,
    paidUSD: 1700,
    startDate: '2026-07-01',
    deadline: '2026-08-20',
    teamCostARS: 500000,
    teamCostUSD: 400,
    description: 'Identidad corporativa, manual de marca, sistema de diseño Figma y kit publicitario.',
    milestones: [
      { name: 'Pago Total 100%', amountARS: 2100000, status: 'Cobrado', date: '2026-08-18' }
    ]
  },
  {
    id: 'proj-4',
    name: 'Portal Web Corporativo',
    client: 'Grupo Inmobiliario Sur',
    category: 'Desarrollo Web',
    status: 'Pendiente Pago',
    budgetARS: 3800000,
    budgetUSD: 3000,
    paidARS: 1900000,
    paidUSD: 1500,
    startDate: '2026-06-10',
    deadline: '2026-09-30',
    teamCostARS: 900000,
    teamCostUSD: 700,
    description: 'Sitio institucional autogestionable con filtro de propiedades en tiempo real y mapas interactivos.',
    milestones: [
      { name: 'Anticipo 50%', amountARS: 1900000, status: 'Cobrado', date: '2026-06-12' },
      { name: 'Final 50%', amountARS: 1900000, status: 'Pendiente', date: '2026-09-05' }
    ]
  },
  {
    id: 'proj-5',
    name: 'Integración Pasarela de Pagos',
    client: 'PayExpress ARG',
    category: 'Backend & API',
    status: 'En Curso',
    budgetARS: 2900000,
    budgetUSD: 2200,
    paidARS: 1450000,
    paidUSD: 1100,
    startDate: '2026-08-01',
    deadline: '2026-10-05',
    teamCostARS: 600000,
    teamCostUSD: 450,
    description: 'Microservicio de pagos multi-moneda con webhooks de seguridad y reintentos automáticos.',
    milestones: [
      { name: 'Anticipo 50%', amountARS: 1450000, status: 'Cobrado', date: '2026-08-03' },
      { name: 'Entrega 50%', amountARS: 1450000, status: 'Pendiente', date: '2026-10-01' }
    ]
  }
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 'tx-101',
    type: 'Ingreso',
    title: 'Cobro Anticipo 50% - E-Commerce SaaS',
    projectId: 'proj-2',
    projectName: 'E-Commerce SaaS B2B',
    client: 'Distribuidora Global S.A.',
    category: 'Software',
    amountARS: 4100000,
    amountUSD: 3200,
    currency: 'ARS',
    status: 'Cobrado',
    date: '2026-05-20',
    method: 'Transferencia Bancaria',
    invoice: 'FACT-00421'
  },
  {
    id: 'tx-102',
    type: 'Ingreso',
    title: 'Sprint 1 UI & Auth - App Móvil',
    projectId: 'proj-1',
    projectName: 'App Móvil Finanzas Pro',
    client: 'FinTech LATAM',
    category: 'Software',
    amountARS: 1650000,
    amountUSD: 1300,
    currency: 'ARS',
    status: 'Cobrado',
    date: '2026-07-20',
    method: 'Mercado Pago',
    invoice: 'FACT-00425'
  },
  {
    id: 'tx-103',
    type: 'Gasto',
    title: 'Servidores AWS Cloud & DB Cluster',
    projectId: 'proj-2',
    projectName: 'E-Commerce SaaS B2B',
    client: 'AWS Cloud',
    category: 'Infraestructura Cloud',
    amountARS: 380000,
    amountUSD: 300,
    currency: 'USD',
    status: 'Pagado',
    date: '2026-08-01',
    method: 'Tarjeta Corporativa',
    invoice: 'AWS-99214'
  },
  {
    id: 'tx-104',
    type: 'Ingreso',
    title: 'Liquidación Total Marca & UI',
    projectId: 'proj-3',
    projectName: 'Rediseño de Marca & UI System',
    client: 'Studio Alpha',
    category: 'UI/UX',
    amountARS: 2100000,
    amountUSD: 1700,
    currency: 'ARS',
    status: 'Cobrado',
    date: '2026-08-18',
    method: 'Transferencia USD (Crypto/Payoneer)',
    invoice: 'INV-2026-088'
  },
  {
    id: 'tx-105',
    type: 'Gasto',
    title: 'Honorarios Senior Backend Dev (Agosto)',
    projectId: 'proj-1',
    projectName: 'App Móvil Finanzas Pro',
    client: 'Freelance Dev Team',
    category: 'Honorarios Devs',
    amountARS: 850000,
    amountUSD: 680,
    currency: 'ARS',
    status: 'Pagado',
    date: '2026-08-30',
    method: 'Transferencia Bancaria',
    invoice: 'REC-098'
  },
  {
    id: 'tx-106',
    type: 'Ingreso',
    title: 'Saldo Pendiente 50% Portal Web',
    projectId: 'proj-4',
    projectName: 'Portal Web Corporativo',
    client: 'Grupo Inmobiliario Sur',
    category: 'Software',
    amountARS: 1900000,
    amountUSD: 1500,
    currency: 'ARS',
    status: 'Pendiente',
    date: '2026-09-05',
    method: 'Transferencia Bancaria',
    invoice: 'FACT-00431'
  },
  {
    id: 'tx-107',
    type: 'Gasto',
    title: 'Licencias Vercel Pro & GitHub Enterprise',
    projectId: 'varios',
    projectName: 'Infraestructura General',
    client: 'Vercel / GitHub',
    category: 'Licencias & Tools',
    amountARS: 160000,
    amountUSD: 125,
    currency: 'USD',
    status: 'Pagado',
    date: '2026-09-02',
    method: 'Tarjeta Corporativa',
    invoice: 'VER-8821'
  },
  {
    id: 'tx-108',
    type: 'Ingreso',
    title: 'Anticipo 50% Integration API',
    projectId: 'proj-5',
    projectName: 'Integración Pasarela de Pagos',
    client: 'PayExpress ARG',
    category: 'Backend & API',
    amountARS: 1450000,
    amountUSD: 1100,
    currency: 'ARS',
    status: 'Cobrado',
    date: '2026-08-03',
    method: 'Mercado Pago',
    invoice: 'FACT-00429'
  },
  {
    id: 'tx-109',
    type: 'Gasto',
    title: 'Diseño 3D & Componentes Adicionales',
    projectId: 'proj-3',
    projectName: 'Rediseño de Marca & UI System',
    client: 'Diseñador Externo',
    category: 'UI/UX',
    amountARS: 250000,
    amountUSD: 200,
    currency: 'ARS',
    status: 'Pagado',
    date: '2026-08-10',
    method: 'Transferencia Bancaria',
    invoice: 'REC-082'
  },
  {
    id: 'tx-110',
    type: 'Ingreso',
    title: 'Sprint 2 Integraciones Finanzas Pro',
    projectId: 'proj-1',
    projectName: 'App Móvil Finanzas Pro',
    client: 'FinTech LATAM',
    category: 'Software',
    amountARS: 1500000,
    amountUSD: 1200,
    currency: 'ARS',
    status: 'Pendiente',
    date: '2026-09-25',
    method: 'Transferencia Bancaria',
    invoice: 'FACT-00435'
  }
];

export const CATEGORIES = {
  Ingreso: ['Software', 'Fullstack Web', 'Branding & UI/UX', 'Backend & API', 'Consultoría', 'Mantenimiento'],
  Gasto: ['Honorarios Devs', 'Infraestructura Cloud', 'Licencias & Tools', 'Marketing & Ads', 'Diseño Externo', 'Impuestos & Comisiones']
};

export const MONTHLY_CASHFLOW = [
  { month: 'Mayo', Ingresos: 4100000, Gastos: 1100000, Balance: 3000000 },
  { month: 'Junio', Ingresos: 3250000, Gastos: 950000, Balance: 2300000 },
  { month: 'Julio', Ingresos: 3750000, Gastos: 1200000, Balance: 2550000 },
  { month: 'Agosto', Ingresos: 5650000, Gastos: 1480000, Balance: 4170000 },
  { month: 'Septiembre (Est.)', Ingresos: 4850000, Gastos: 1260000, Balance: 3590000 },
];
